spring:
  application:
    name: car_park_bot
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate

bot:
  token:
  username: car_park_report_bot
  creator-id:
app:
  login-url:
  mileage-report-url: